#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rbconfig'

warn 'script/package-homebrew-release is deprecated; use script/assemble-homebrew-release instead.'
exec RbConfig.ruby, File.join(__dir__, 'assemble-homebrew-release'), *ARGV
