#!/usr/bin/env ruby
# frozen_string_literal: true

require 'find'
require 'optparse'
require_relative 'release_support'

options = {}
OptionParser.new do |parser|
  parser.on('--config PATH') { |path| options[:config] = File.expand_path(path) }
  parser.on('--target TARGET', FeedMobRelease::TARGET_IDS) { |target| options[:target] = target }
end.parse!

config_path = options.fetch(:config, File.expand_path('../packaging/release.yml', __dir__))
target_id = options.fetch(:target)
config = FeedMobRelease.load_config(config_path)
target = FeedMobRelease.target!(config, target_id)
FeedMobRelease.assert_native_target!(target_id, target)
root = File.expand_path(ARGV.fetch(0))
native_count = 0

Find.find(root) do |path|
  next unless File.file?(path)

  if target.fetch('os') == 'macos'
    next unless FeedMobRelease.macho_architectures(path)
  else
    next unless FeedMobRelease.elf?(path)
  end

  native_count += 1
  FeedMobRelease.validate_binary_format!(path, target)
  FeedMobRelease.verify_glibc_requirement!(path, target)
end

format = target.fetch('os') == 'macos' ? 'Mach-O' : 'ELF'
puts "Embedded #{format} files: #{native_count}"
